name: Kis Deploy

on:
  push: 
    branches:
      - master
      
jobs:
  build: 
    runs-on: self-hosted
    
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy Frontend
      run: |
          cd /repository/kis
          git pull
          cd frontend
          yarn build
          rm -r -f /var/www/kis.kopikoding.com/public_html/*
          cp -R /repository/kis/frontend/dist/* /var/www/kis.kopikoding.com/public_html/
    - name: Deploy Backend
      run: |
          cd /repository/kis
          git pull
          cd backend
          rm -r -f /var/www/kis.kopikoding.com/public_html/api/*
          cp -R /repository/kis/backend/* /var/www/kis.kopikoding.com/public_html/api/
